"""Add unique key to users.email

Revision ID: 20753ae4ab5
Revises: 4771f0d06e5
Create Date: 2014-08-06 19:31:33.751428

"""

# revision identifiers, used by Alembic.
revision = '20753ae4ab5'
down_revision = '4771f0d06e5'

from alembic import context
from alembic.op import create_unique_constraint, drop_constraint


def upgrade():
    ### commands auto generated by Alembic - please adjust! ##
    bind = context.get_bind()
    if bind.dialect.name == 'postgresql':
        create_unique_constraint('users_email_key', 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = context.get_bind()
    if bind.dialect.name == 'postgresql':
        drop_constraint('users_email_key', 'users')
    ### end Alembic commands ###
